repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/hakancelikdev/unimport
    rev: 1.2.1
    hooks:
      - id: unimport
        args:
          - --include-star-import
          - --ignore-init
          - --gitignore
