/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/rwTSgVn5ARK
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Toggle } from "@/components/ui/toggle";
import { Dispatch, SetStateAction } from "react";
import { Network } from "@mintbase-js/sdk";

export function NetworkToggle({
  network,
  setNetwork,
}: {
  network: Network;
  setNetwork: Dispatch<SetStateAction<Network>>;
}) {
  const selectedClass =
    "bg-gray-800 text-gray-50 hover:bg-gray-700 focus:z-10 dark:bg-gray-100 dark:text-gray-900 dark:hover:bg-gray-200";
  const unselectedClass =
    "bg-gray-100 text-gray-900 hover:bg-gray-200 focus:z-10 dark:bg-gray-800 dark:text-gray-50 dark:hover:bg-gray-700";
  return (
    <header className="flex h-20 w-full shrink-0 items-center px-4 md:px-6 absolute right-0 top-0">
      <div className="ml-auto flex items-center gap-4">
        <Toggle aria-label="Toggle network" className="flex items-center">
          <div
            onClick={() => setNetwork("mainnet")}
            className={`px-4 py-2 text-sm font-medium rounded-l-md ${
              network === "mainnet" ? selectedClass : unselectedClass
            } transition-colors duration-200 ease-in-out`}
          >
            Mainnet
          </div>
          <div
            onClick={() => setNetwork("testnet")}
            className={`px-4 py-2 text-sm font-medium rounded-l-md ${
              network === "testnet" ? selectedClass : unselectedClass
            } transition-colors duration-200 ease-in-out`}
          >
            Testnet
          </div>
        </Toggle>
      </div>
    </header>
  );
}
